### ISSUE TITLE
Example with MolecularGraphBatchGenerator?

### ISSUE THREAD

**Issue by tawe141** [materialsvirtuallab/megnet#13]
This looks like a very convenient way to go from SMILES strings to feature vectors that MEGNet can use, but I'm not sure how to use it. I have a very simple script:

```
import pandas as pd
import tensorflow as tf
from megnet.data.molecule import MolecularGraphBatchGenerator
from megnet.models import MEGNetModel
from math import ceil

tf.random.set_random_seed(42)

df = pd.read_pickle('dataset/uvvis_train.pickle')
df = df[['Structure', 'mean_rj']]

batch_size = 100

train_generator = MolecularGraphBatchGenerator(
    mols=df['Structure'],
    targets=df['mean_rj'].values,
    molecule_format='smiles',
    batch_size=batch_size,
)

model = MEGNetModel(10, 2, nblocks=1, lr=1e-2,
                    n1=4, n2=4, n3=4, npass=1, ntarget=1)

n_steps_per_epoch = ceil(len(df) / batch_size)

model.fit_generator(train_generator, steps_per_epoch=n_steps_per_epoch, verbose=1, epochs=10)
```

However, this fails with the following error:

```
Traceback (most recent call last):
  File "/home/erictaw/PycharmProjects/experimental_uv_vis/models/megnet_test/megnet_test.py", line 26, in <module>
    model.fit_generator(train_generator, steps_per_epoch=n_steps_per_epoch, verbose=1, epochs=10)
  File "/home/erictaw/miniconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/erictaw/miniconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/erictaw/miniconda3/lib/python3.6/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/erictaw/miniconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1211, in train_on_batch
    class_weight=class_weight)
  File "/home/erictaw/miniconda3/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/home/erictaw/miniconda3/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 2 dimensions, but got array with shape (1, 5626, 44)
```
How do you use this generator, and why is there a dimension error?

**Comment by chc273** [comment]
Hi @tawe141, 

By default, MEGNet model takes the atom feature for each atom to be just the atomic number (integer). Here, the `MolecularGraphBatchGenerator` generated a specific molecular graph where the atom features for each atom is a vector. Therefore you need to set `nfeat_node` in `MEGNetModel` initializer. 

The `nfeat_node` should be set to `train_generator en[0][0][0].shape[-1]`. Please see if this solves your problem. Otherwise please share a minimal dataset that I can work with to solve the issue.

**Comment by chc273** [comment]
@tawe141  please also check the example for molecule graphs and model training

https://github.com/materialsvirtuallab/megnet/blob/master/notebooks/molecule_example.ipynb

**Comment by tawe141** [comment]
Perfect! Thanks @chc273
