### ISSUE TITLE
Got nan in loss

### ISSUE THREAD

**Issue by nd-02110114** [materialsvirtuallab/megnet#19]
@chc273 

Hi, I create train script for learning from qm9's xyz file.
The following dir is reproducing directory.
https://github.com/nd-02110114/megnet/tree/repro/repro

If the number of data is so small (100), this script works 👍 
However, If the number of data is large (1000~), 
this script doesn't works... I got nan in loss. 

How should I do in order to avoid getting nan in loss ?
This script's hyper param setting is worse...?

The below log is sample.

```
Epoch 1/10

 1/25 [>.............................] - ETA: 2:54 - loss: 0.0612
 2/25 [=>............................] - ETA: 1:31 - loss: 0.0318
 3/25 [==>...........................] - ETA: 1:03 - loss: 0.0257
 4/25 [===>..........................] - ETA: 49s - loss: 0.0241
 5/25 [=====>........................] - ETA: 40s - loss: 0.0212
 6/25 [======>.......................] - ETA: 33s - loss: 0.0182
 7/25 [=======>......................] - ETA: 29s - loss: 0.0159
 8/25 [========>.....................] - ETA: 25s - loss: 0.0145
 9/25 [=========>....................] - ETA: 22s - loss: nan
10/25 [===========>..................] - ETA: 20s - loss: nan
11/25 [============>.................] - ETA: 17s - loss: nan
12/25 [=============>................] - ETA: 15s - loss: nan
13/25 [==============>...............] - ETA: 14s - loss: nan
14/25 [===============>..............] - ETA: 12s - loss: nan
15/25 [=================>............] - ETA: 10s - loss: nan
16/25 [==================>...........] - ETA: 9s - loss: nan
17/25 [===================>..........] - ETA: 8s - loss: nan
18/25 [====================>.........] - ETA: 7s - loss: nan
19/25 [=====================>........] - ETA: 5s - loss: nan
20/25 [=======================>......] - ETA: 4s - loss: nan
21/25 [========================>.....] - ETA: 3s - loss: nan
22/25 [=========================>....] - ETA: 2s - loss: nan
23/25 [==========================>...] - ETA: 1s - loss: nan
24/25 [===========================>..] - ETA: 0s - loss: nan
25/25 [==============================] - 24s 952ms/step - loss: nan - val_loss: nan
I0819 07:17:08.106158 140691671836480 callbacks.py:272] Nan loss found!
I0819 07:17:09.059619 140691671836480 callbacks.py:295] No weights were loaded
I0819 07:17:09.905934 140691671836480 callbacks.py:275] Now lr is 0.0005000000237487257.
Epoch 2/10

 1/25 [>.............................] - ETA: 5:16 - loss: nan
 2/25 [=>............................] - ETA: 2:43 - loss: nan
 3/25 [==>...........................] - ETA: 1:52 - loss: nan
 4/25 [===>..........................] - ETA: 1:25 - loss: nan
 5/25 [=====>........................] - ETA: 1:09 - loss: nan
 6/25 [======>.......................] - ETA: 57s - loss: nan
 7/25 [=======>......................] - ETA: 48s - loss: nan
 8/25 [========>.....................] - ETA: 42s - loss: nan
 9/25 [=========>....................] - ETA: 37s - loss: nan
10/25 [===========>..................] - ETA: 33s - loss: nan
11/25 [============>.................] - ETA: 29s - loss: nan
12/25 [=============>................] - ETA: 25s - loss: nan
13/25 [==============>...............] - ETA: 22s - loss: nan
14/25 [===============>..............] - ETA: 19s - loss: nan
15/25 [=================>............] - ETA: 16s - loss: nan
16/25 [==================>...........] - ETA: 14s - loss: nan
17/25 [===================>..........] - ETA: 12s - loss: nan
18/25 [====================>.........] - ETA: 10s - loss: nan
19/25 [=====================>........] - ETA: 8s - loss: nan
20/25 [=======================>......] - ETA: 7s - loss: nan
21/25 [========================>.....] - ETA: 5s - loss: nan
22/25 [=========================>....] - ETA: 4s - loss: nan
23/25 [==========================>...] - ETA: 2s - loss: nan
```

**Comment by nd-02110114** [comment]
If the number of data is larger (10000~),
this script doesn't works... I got another error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/megnet/models.py", line 221, in get_all_graphs_targets
    graph = self.graph_converter.convert(s)
  File "/usr/local/lib/python3.6/dist-packages/megnet/data/molecule.py", line 167, in convert
    i.update({'graph_distance': graph_dist[i['a_idx'], i['b_idx']]})
IndexError: index 13 is out of bounds for axis 1 with size 13

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 109, in <module>
    main(parse())
  File "train.py", line 104, in main
    epochs=args.epoch, batch_size=args.batchsize, verbose=1)
  File "/usr/local/lib/python3.6/dist-packages/megnet/models.py", line 81, in train
    scrub_failed_structures=scrub_failed_structures)
  File "/usr/local/lib/python3.6/dist-packages/megnet/models.py", line 230, in get_all_graphs_targets
    raise RuntimeError(str(e))
RuntimeError: index 13 is out of bounds for axis 1 with size 13
```

**Comment by chc273** [comment]
@nd-02110114 For the first nan problem, it is a common issue with deep learning based regression. The model generally does not handle well big output numbers. Two things can be done here, 1. Scale your output to smaller numbers, for example by subtracting  the mean and divided by the standard deviation, or by range scaling (x-min)/(max-min). 2. Reduce the learning rate.

**Comment by chc273** [comment]
For the second issue, I cannot tell much from the error msg, could you track down the molecule that gives you this error? It is not a problem with data size, but rather a specific molecule that failed the graph computation. @nd-02110114
