### ISSUE TITLE
Failed to convert a NumPy array to a Tensor (Unsupported numpy type: NPY_INT).

### ISSUE THREAD

**Issue by dinhanhminh** [materialsvirtuallab/megnet#52]
Hi, 
I ran into this error trying to run the commands showed in the examples and the notebooks. Was this because of some incompatibilities between versions of tensorflow and megnet? 
Thanks,
Minh

**Comment by chc273** [comment]
Could you give reproducible details? Which example did you run? Which line is cause the error?

**Comment by dinhanhminh** [comment]
Thanks for the swift reply. 
Here is the code that I was trying to run
``` import numpy as np 
from monty.json import MontyDecoder
from monty.serialization import loadfn

data = loadfn('bulk_moduli.json')
structures = data['structures']
targets = np.log10(data['bulk_moduli'])

from megnet.data.crystal import CrystalGraph
from megnet.data.graph import GaussianDistance
from megnet.models import MEGNetModel

model = MEGNetModel(10, 2, nblocks=1, lr=1e-2,
                    n1=4, n2=4, n3=4, npass=1, ntarget=1,
                    graph_converter=CrystalGraph(bond_converter=GaussianDistance(np.linspace(0, 5, 10), 0.5)))


model.train(structures, targets, epochs=2)
```

And here is the output

```
runfile('C:/Users/minhdinh/Downloads/megnet-master/test.py', wdir='C:/Users/minhdinh/Downloads/megnet-master')
C:\Users\minhdinh\Anaconda3\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Epoch 1/2
Traceback (most recent call last):

  File "<ipython-input-7-631f0b76bd61>", line 1, in <module>
    runfile('C:/Users/minhdinh/Downloads/megnet-master/test.py', wdir='C:/Users/minhdinh/Downloads/megnet-master')

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/minhdinh/Downloads/megnet-master/test.py", line 18, in <module>
    model.train(structures, targets, epochs=2)

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\megnet\models.py", line 117, in train
    **kwargs

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\megnet\models.py", line 204, in train_from_graphs
    epochs=epochs, verbose=verbose, callbacks=callbacks, **kwargs)

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\keras\engine\training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\keras\engine\training_generator.py", line 220, in fit_generator
    reset_metrics=False)

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\keras\engine\training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3734, in __call__
    value = ops.convert_to_tensor(value, dtype=tensor.dtype)

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_conversion_registry.py", line 52, in _default_conversion_function
    return constant_op.constant(value, dtype, name=name)

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 227, in constant
    allow_broadcast=True)

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 235, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)

  File "C:\Users\minhdinh\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported numpy type: NPY_INT).

**Comment by chc273** [comment]
The error is not reproducible. The code runs fine on my end. Please make sure to update all its dependencies, e.g.,` tensorflow-2.0` etc. You can install the dependencies by `pip install -r requirements.txt` using the `requirements.txt` in the repo.

**Comment by dinhanhminh** [comment]
I have run the `pip install -r requirements.txt` and updated all the required modules but the error still shows. I am running python 3.7 by the way. Would that potentially cause the said error?

**Comment by dinhanhminh** [comment]
Error still shows for python 3.6

**Comment by chc273** [comment]
Check the versions of all megnet dependencies, and see if they match with “requirements.txt”. It’s not the problem of python version.

**Comment by goodwilling** [comment]
sorry to bother here. I met the same error no matter what version I tried on Windows 10:
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported numpy type: NPY_INT

Some tests show that the array x passed to ops.convert_to_tensor(x) is like: 

[[13 13 13 13 71 71]]
[[[5.61047089e-40 5.54019603e-39 5.31238221e-38 ... 6.30694114e-03
   3.60135342e-03 1.99687588e-03]
  [5.61047127e-40 5.54019640e-39 5.31238256e-38 ... 6.30694104e-03
   3.60135336e-03 1.99687584e-03]
  [5.61047046e-40 5.54019562e-39 5.31238182e-38 ... 6.30694125e-03
   3.60135349e-03 1.99687592e-03]
  ...
  [1.02319409e-18 4.79948017e-18 2.18609355e-17 ... 5.03132447e-13
   1.36470773e-13 3.59447392e-14]
  [1.02319415e-18 4.79948044e-18 2.18609367e-17 ... 5.03132423e-13
   1.36470766e-13 3.59447374e-14]
  [2.36864315e-20 1.19087640e-19 5.81396086e-19 ... 9.74807241e-12
   2.83404633e-12 8.00080170e-13]]]
[[[0 0]]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
  3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4
  4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]]

Can this array be converted to a tensor without problem?

**Comment by chc273** [comment]
This ssems to be related to tensorflow version. Which tensorflow version are you using? 

you can find it by

import tensorflow
print(tensorflow.__version__).


Please make sure that all dependency packages have the same version as 'requirements.txt'. Also sometimes, put this line at the beginning of your code is needed: import tensorflow

**Comment by chc273** [comment]
Note that this is not a problem with megnet, but rather the tensorflow package. You can find similar issues on tensorflow repo as well.

**Comment by goodwilling** [comment]
Thank you for your comment.  I have tried various versions of tensorflow on Windows 10 but still got the same problem. 
By  the way,  similar problem can be seen in the case of tensorflow 2.0 on RHEL 7: 

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported numpy type: NPY_LONGLONG)

This problem has been solved using tensorflow 2.1.0 on RHEL 7, but not on Windows 10.

**Comment by goodwilling** [comment]
I have also tried tf-nightly, but the problem still exists.

>>> import tensorflow
>>> tensorflow.__version__
'2.2.0-dev20200425'

**Comment by chc273** [comment]
Thats weird on windows.. Could you try setting up a python virtual environment on windows machine and install megnet from scratch?
First find requirements.txt in the repo and install the dependeny by 'pip install -r requirements.txt'. Then install megnet using setup.py.

**Comment by chc273** [comment]
I just noticed a potential fix for this. in your script, disable eager execution may suppress this error. I'd suggest you  do so for performance consideration as well.

```
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
```
